name: specs_gen_workflow

on:
  pull_request:
    branches:
      - dev

jobs: 
  build_docs_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run pylint
        run: |
          make pylint

      - name: Run tests
        run: |
          make test

